// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.4
// source: federation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeliverMessageResponse_Status int32

const (
	DeliverMessageResponse_ACCEPTED                DeliverMessageResponse_Status = 0
	DeliverMessageResponse_REJECTED_NO_SUCH_USER   DeliverMessageResponse_Status = 1
	DeliverMessageResponse_REJECTED_QUOTA_EXCEEDED DeliverMessageResponse_Status = 2
	DeliverMessageResponse_REJECTED_RATE_LIMITED   DeliverMessageResponse_Status = 3
	DeliverMessageResponse_REJECTED_BLOCKED        DeliverMessageResponse_Status = 4
)

// Enum value maps for DeliverMessageResponse_Status.
var (
	DeliverMessageResponse_Status_name = map[int32]string{
		0: "ACCEPTED",
		1: "REJECTED_NO_SUCH_USER",
		2: "REJECTED_QUOTA_EXCEEDED",
		3: "REJECTED_RATE_LIMITED",
		4: "REJECTED_BLOCKED",
	}
	DeliverMessageResponse_Status_value = map[string]int32{
		"ACCEPTED":                0,
		"REJECTED_NO_SUCH_USER":   1,
		"REJECTED_QUOTA_EXCEEDED": 2,
		"REJECTED_RATE_LIMITED":   3,
		"REJECTED_BLOCKED":        4,
	}
)

func (x DeliverMessageResponse_Status) Enum() *DeliverMessageResponse_Status {
	p := new(DeliverMessageResponse_Status)
	*p = x
	return p
}

func (x DeliverMessageResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeliverMessageResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_federation_proto_enumTypes[0].Descriptor()
}

func (DeliverMessageResponse_Status) Type() protoreflect.EnumType {
	return &file_federation_proto_enumTypes[0]
}

func (x DeliverMessageResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeliverMessageResponse_Status.Descriptor instead.
func (DeliverMessageResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{2, 0}
}

type DeliverMessageRequest struct {
	state                 protoimpl.MessageState     `protogen:"open.v1"`
	Sender                string                     `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient             string                     `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	EncryptedMessage      []byte                     `protobuf:"bytes,3,opt,name=encrypted_message,json=encryptedMessage,proto3" json:"encrypted_message,omitempty"`
	Metadata              *FederationMessageMetadata `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	SenderServerSignature []byte                     `protobuf:"bytes,5,opt,name=sender_server_signature,json=senderServerSignature,proto3" json:"sender_server_signature,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *DeliverMessageRequest) Reset() {
	*x = DeliverMessageRequest{}
	mi := &file_federation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverMessageRequest) ProtoMessage() {}

func (x *DeliverMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverMessageRequest.ProtoReflect.Descriptor instead.
func (*DeliverMessageRequest) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{0}
}

func (x *DeliverMessageRequest) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *DeliverMessageRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *DeliverMessageRequest) GetEncryptedMessage() []byte {
	if x != nil {
		return x.EncryptedMessage
	}
	return nil
}

func (x *DeliverMessageRequest) GetMetadata() *FederationMessageMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DeliverMessageRequest) GetSenderServerSignature() []byte {
	if x != nil {
		return x.SenderServerSignature
	}
	return nil
}

type FederationMessageMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FederationMessageMetadata) Reset() {
	*x = FederationMessageMetadata{}
	mi := &file_federation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FederationMessageMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FederationMessageMetadata) ProtoMessage() {}

func (x *FederationMessageMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FederationMessageMetadata.ProtoReflect.Descriptor instead.
func (*FederationMessageMetadata) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{1}
}

func (x *FederationMessageMetadata) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *FederationMessageMetadata) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FederationMessageMetadata) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

type DeliverMessageResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Status        DeliverMessageResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=mailx.federation.v1.DeliverMessageResponse_Status" json:"status,omitempty"`
	MessageId     string                        `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Timestamp     int64                         `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ErrorMessage  string                        `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverMessageResponse) Reset() {
	*x = DeliverMessageResponse{}
	mi := &file_federation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverMessageResponse) ProtoMessage() {}

func (x *DeliverMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverMessageResponse.ProtoReflect.Descriptor instead.
func (*DeliverMessageResponse) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{2}
}

func (x *DeliverMessageResponse) GetStatus() DeliverMessageResponse_Status {
	if x != nil {
		return x.Status
	}
	return DeliverMessageResponse_ACCEPTED
}

func (x *DeliverMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DeliverMessageResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DeliverMessageResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ServerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfoRequest) Reset() {
	*x = ServerInfoRequest{}
	mi := &file_federation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoRequest) ProtoMessage() {}

func (x *ServerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoRequest.ProtoReflect.Descriptor instead.
func (*ServerInfoRequest) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{3}
}

func (x *ServerInfoRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type ServerInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities  *ServerCapabilities    `protobuf:"bytes,4,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfoResponse) Reset() {
	*x = ServerInfoResponse{}
	mi := &file_federation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoResponse) ProtoMessage() {}

func (x *ServerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoResponse.ProtoReflect.Descriptor instead.
func (*ServerInfoResponse) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{4}
}

func (x *ServerInfoResponse) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ServerInfoResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *ServerInfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServerInfoResponse) GetCapabilities() *ServerCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type ServerCapabilities struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SupportsE2Ee   bool                   `protobuf:"varint,1,opt,name=supports_e2ee,json=supportsE2ee,proto3" json:"supports_e2ee,omitempty"`
	MaxMessageSize int32                  `protobuf:"varint,2,opt,name=max_message_size,json=maxMessageSize,proto3" json:"max_message_size,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServerCapabilities) Reset() {
	*x = ServerCapabilities{}
	mi := &file_federation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerCapabilities) ProtoMessage() {}

func (x *ServerCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerCapabilities.ProtoReflect.Descriptor instead.
func (*ServerCapabilities) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{5}
}

func (x *ServerCapabilities) GetSupportsE2Ee() bool {
	if x != nil {
		return x.SupportsE2Ee
	}
	return false
}

func (x *ServerCapabilities) GetMaxMessageSize() int32 {
	if x != nil {
		return x.MaxMessageSize
	}
	return 0
}

type GetUserKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // alice@example.com
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserKeyRequest) Reset() {
	*x = GetUserKeyRequest{}
	mi := &file_federation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserKeyRequest) ProtoMessage() {}

func (x *GetUserKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserKeyRequest.ProtoReflect.Descriptor instead.
func (*GetUserKeyRequest) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserKeyRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetUserKeyResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Address         string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PublicKey       []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	ServerSignature []byte                 `protobuf:"bytes,3,opt,name=server_signature,json=serverSignature,proto3" json:"server_signature,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetUserKeyResponse) Reset() {
	*x = GetUserKeyResponse{}
	mi := &file_federation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserKeyResponse) ProtoMessage() {}

func (x *GetUserKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_federation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserKeyResponse.ProtoReflect.Descriptor instead.
func (*GetUserKeyResponse) Descriptor() ([]byte, []int) {
	return file_federation_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserKeyResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetUserKeyResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *GetUserKeyResponse) GetServerSignature() []byte {
	if x != nil {
		return x.ServerSignature
	}
	return nil
}

func (x *GetUserKeyResponse) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_federation_proto protoreflect.FileDescriptor

const file_federation_proto_rawDesc = "" +
	"\n" +
	"\x10federation.proto\x12\x13mailx.federation.v1\"\xfe\x01\n" +
	"\x15DeliverMessageRequest\x12\x16\n" +
	"\x06sender\x18\x01 \x01(\tR\x06sender\x12\x1c\n" +
	"\trecipient\x18\x02 \x01(\tR\trecipient\x12+\n" +
	"\x11encrypted_message\x18\x03 \x01(\fR\x10encryptedMessage\x12J\n" +
	"\bmetadata\x18\x04 \x01(\v2..mailx.federation.v1.FederationMessageMetadataR\bmetadata\x126\n" +
	"\x17sender_server_signature\x18\x05 \x01(\fR\x15senderServerSignature\"g\n" +
	"\x19FederationMessageMetadata\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\"\xc7\x02\n" +
	"\x16DeliverMessageResponse\x12J\n" +
	"\x06status\x18\x01 \x01(\x0e22.mailx.federation.v1.DeliverMessageResponse.StatusR\x06status\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\x7f\n" +
	"\x06Status\x12\f\n" +
	"\bACCEPTED\x10\x00\x12\x19\n" +
	"\x15REJECTED_NO_SUCH_USER\x10\x01\x12\x1b\n" +
	"\x17REJECTED_QUOTA_EXCEEDED\x10\x02\x12\x19\n" +
	"\x15REJECTED_RATE_LIMITED\x10\x03\x12\x14\n" +
	"\x10REJECTED_BLOCKED\x10\x04\"+\n" +
	"\x11ServerInfoRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"\xb2\x01\n" +
	"\x12ServerInfoResponse\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12K\n" +
	"\fcapabilities\x18\x04 \x01(\v2'.mailx.federation.v1.ServerCapabilitiesR\fcapabilities\"c\n" +
	"\x12ServerCapabilities\x12#\n" +
	"\rsupports_e2ee\x18\x01 \x01(\bR\fsupportsE2ee\x12(\n" +
	"\x10max_message_size\x18\x02 \x01(\x05R\x0emaxMessageSize\"-\n" +
	"\x11GetUserKeyRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"\x97\x01\n" +
	"\x12GetUserKeyResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12)\n" +
	"\x10server_signature\x18\x03 \x01(\fR\x0fserverSignature\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt2\xbf\x02\n" +
	"\x11FederationService\x12i\n" +
	"\x0eDeliverMessage\x12*.mailx.federation.v1.DeliverMessageRequest\x1a+.mailx.federation.v1.DeliverMessageResponse\x12`\n" +
	"\rGetServerInfo\x12&.mailx.federation.v1.ServerInfoRequest\x1a'.mailx.federation.v1.ServerInfoResponse\x12]\n" +
	"\n" +
	"GetUserKey\x12&.mailx.federation.v1.GetUserKeyRequest\x1a'.mailx.federation.v1.GetUserKeyResponseB/Z-github.com/albahrani/mailx/client/proto;protob\x06proto3"

var (
	file_federation_proto_rawDescOnce sync.Once
	file_federation_proto_rawDescData []byte
)

func file_federation_proto_rawDescGZIP() []byte {
	file_federation_proto_rawDescOnce.Do(func() {
		file_federation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_federation_proto_rawDesc), len(file_federation_proto_rawDesc)))
	})
	return file_federation_proto_rawDescData
}

var file_federation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_federation_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_federation_proto_goTypes = []any{
	(DeliverMessageResponse_Status)(0), // 0: mailx.federation.v1.DeliverMessageResponse.Status
	(*DeliverMessageRequest)(nil),      // 1: mailx.federation.v1.DeliverMessageRequest
	(*FederationMessageMetadata)(nil),  // 2: mailx.federation.v1.FederationMessageMetadata
	(*DeliverMessageResponse)(nil),     // 3: mailx.federation.v1.DeliverMessageResponse
	(*ServerInfoRequest)(nil),          // 4: mailx.federation.v1.ServerInfoRequest
	(*ServerInfoResponse)(nil),         // 5: mailx.federation.v1.ServerInfoResponse
	(*ServerCapabilities)(nil),         // 6: mailx.federation.v1.ServerCapabilities
	(*GetUserKeyRequest)(nil),          // 7: mailx.federation.v1.GetUserKeyRequest
	(*GetUserKeyResponse)(nil),         // 8: mailx.federation.v1.GetUserKeyResponse
}
var file_federation_proto_depIdxs = []int32{
	2, // 0: mailx.federation.v1.DeliverMessageRequest.metadata:type_name -> mailx.federation.v1.FederationMessageMetadata
	0, // 1: mailx.federation.v1.DeliverMessageResponse.status:type_name -> mailx.federation.v1.DeliverMessageResponse.Status
	6, // 2: mailx.federation.v1.ServerInfoResponse.capabilities:type_name -> mailx.federation.v1.ServerCapabilities
	1, // 3: mailx.federation.v1.FederationService.DeliverMessage:input_type -> mailx.federation.v1.DeliverMessageRequest
	4, // 4: mailx.federation.v1.FederationService.GetServerInfo:input_type -> mailx.federation.v1.ServerInfoRequest
	7, // 5: mailx.federation.v1.FederationService.GetUserKey:input_type -> mailx.federation.v1.GetUserKeyRequest
	3, // 6: mailx.federation.v1.FederationService.DeliverMessage:output_type -> mailx.federation.v1.DeliverMessageResponse
	5, // 7: mailx.federation.v1.FederationService.GetServerInfo:output_type -> mailx.federation.v1.ServerInfoResponse
	8, // 8: mailx.federation.v1.FederationService.GetUserKey:output_type -> mailx.federation.v1.GetUserKeyResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_federation_proto_init() }
func file_federation_proto_init() {
	if File_federation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_federation_proto_rawDesc), len(file_federation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_federation_proto_goTypes,
		DependencyIndexes: file_federation_proto_depIdxs,
		EnumInfos:         file_federation_proto_enumTypes,
		MessageInfos:      file_federation_proto_msgTypes,
	}.Build()
	File_federation_proto = out.File
	file_federation_proto_goTypes = nil
	file_federation_proto_depIdxs = nil
}
